### ISSUE TITLE
Off-by-one error in dates

### ISSUE THREAD

**Issue by xenotropic** [awhitty/find-campsite#7]
I noticed that I wasn't getting results for a date when I should, and it seems like there is an off-by one error somewhere. I'll see if I can pinpoint further (I want this thing to work so I can find a campsite!), but reporting in case I don't get to it. If one asks for sites on a Friday, what you actually get is Saturday. If you ask for Thursday, then you get Friday. Here's an example showing results from the find-campsite, and from reservecalifornia at the same time, in which I in fact asked for a Thursday and got Friday's availability 

![image](https://user-images.githubusercontent.com/4050617/135324949-f184f8c7-2a77-4e7f-838b-d3d5b7d0773d.png)

![image](https://user-images.githubusercontent.com/4050617/135325114-5c5b27af-d174-4359-9638-eb092d04d9e1.png)

**Comment by awhitty** [comment]
Thanks for the issue! This should be fixed, but let me know if you see anything else. Also happy to receive any feedback any other improvements. The goal is to spend time camping, not using computers.
